type CellValue=string|number|boolean|null|undefined
type Worksheet=Record<string,unknown>&{'!data'?:CellValue[][],'!cols'?:{wch?:number}[]}
type Workbook={SheetNames:string[],Sheets:Record<string,Worksheet>}
const esc=(v:unknown)=>String(v??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!))
const letters=(n:number)=>{let s='';for(n+=1;n>0;n=Math.floor((n-1)/26))s=String.fromCharCode(((n-1)%26)+65)+s;return s}
const crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1);return c>>>0})
const crc32=(buf:Uint8Array)=>{let c=0xffffffff;for(const b of buf)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
const u16=(n:number)=>[n&255,(n>>>8)&255],u32=(n:number)=>[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]
function zip(files:{name:string;content:string}[]){const parts:Uint8Array[]=[];const central:Uint8Array[]=[];let offset=0;const enc=new TextEncoder();for(const f of files){const name=enc.encode(f.name),data=enc.encode(f.content),crc=crc32(data);const local=new Uint8Array([...u32(0x04034b50),...u16(20),0,0,0,0,0,0,0,0,...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),0,0,...name,...data]);parts.push(local);central.push(new Uint8Array([...u32(0x02014b50),20,0,20,0,0,0,0,0,0,0,0,...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),0,0,0,0,0,0,0,0,0,0,...u32(offset),...name]));offset+=local.length}const centralSize=central.reduce((a,b)=>a+b.length,0);const end=new Uint8Array([...u32(0x06054b50),0,0,0,0,...u16(files.length),...u16(files.length),...u32(centralSize),...u32(offset),0,0]);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function sheetXml(ws:Worksheet){const rows=ws['!data']??[];const maxCols=Math.max(...rows.map(r=>r.length),0);const dimension=rows.length&&maxCols?`<dimension ref="A1:${letters(maxCols-1)}${rows.length}"/>`:'';const cols=ws['!cols']?.length?`<cols>${ws['!cols'].map((c,i)=>`<col min="${i+1}" max="${i+1}" width="${c.wch??10}" customWidth="1"/>`).join('')}</cols>`:'';const sheetData=rows.map((row,i)=>`<row r="${i+1}">${row.map((value,j)=>{if(value===null||value===undefined)return '';const ref=`${letters(j)}${i+1}`;return typeof value==='number'?`<c r="${ref}"><v>${value}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t>${esc(value)}</t></is></c>`}).join('')}</row>`).join('');return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">${dimension}${cols}<sheetData>${sheetData}</sheetData></worksheet>`}
export const utils={aoa_to_sheet(data:CellValue[][]):Worksheet{return {'!data':data}},book_new():Workbook{return {SheetNames:[],Sheets:{}}},book_append_sheet(wb:Workbook,ws:Worksheet,name:string){wb.SheetNames.push(name);wb.Sheets[name]=ws}}
export function writeFile(workbook:Workbook,filename:string,options?:{bookType?:'xlsx',compression?:boolean}){void options;const sheetName=workbook.SheetNames[0];const worksheet=workbook.Sheets[sheetName];const blob=zip([{name:'[Content_Types].xml',content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'},{name:'_rels/.rels',content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'},{name:'xl/workbook.xml',content:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${esc(sheetName)}" sheetId="1" r:id="rId1"/></sheets></workbook>`},{name:'xl/_rels/workbook.xml.rels',content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'},{name:'xl/worksheets/sheet1.xml',content:sheetXml(worksheet)}]);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
