type CellValue=string|number|boolean|null|undefined
type Worksheet=Record<string,unknown>&{'!data'?:CellValue[][],'!cols'?:{wch?:number}[],'!freeze'?:{ySplit?:number},'!autofilter'?:{ref:string}}
type Workbook={SheetNames:string[],Sheets:Record<string,Worksheet>}
const esc=(v:unknown)=>String(v??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!))
const letters=(n:number)=>{let s='';for(n+=1;n>0;n=Math.floor((n-1)/26))s=String.fromCharCode(((n-1)%26)+65)+s;return s}
const crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1);return c>>>0})
const crc32=(buf:Uint8Array)=>{let c=0xffffffff;for(const b of buf)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
const u16=(n:number)=>[n&255,(n>>>8)&255],u32=(n:number)=>[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]
function zip(files:{name:string;content:string}[]){const parts:Uint8Array[]=[];const central:Uint8Array[]=[];let offset=0;const enc=new TextEncoder();for(const f of files){const name=enc.encode(f.name),data=enc.encode(f.content),crc=crc32(data);const local=new Uint8Array([...u32(0x04034b50),...u16(20),0,0,0,0,0,0,0,0,...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),0,0,...name,...data]);parts.push(local);central.push(new Uint8Array([...u32(0x02014b50),20,0,20,0,0,0,0,0,0,0,0,...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),0,0,0,0,0,0,0,0,0,0,...u32(offset),...name]));offset+=local.length}const centralSize=central.reduce((a,b)=>a+b.length,0);const end=new Uint8Array([...u32(0x06054b50),0,0,0,0,...u16(files.length),...u16(files.length),...u32(centralSize),...u32(offset),0,0]);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function sheetXml(ws:Worksheet){const rows=ws['!data']??[];const maxCols=Math.max(...rows.map(r=>r.length),0);const dimension=rows.length&&maxCols?`<dimension ref="A1:${letters(maxCols-1)}${rows.length}"/>`:'';const cols=ws['!cols']?.length?`<cols>${ws['!cols'].map((c,i)=>`<col min="${i+1}" max="${i+1}" width="${c.wch??10}" customWidth="1"/>`).join('')}</cols>`:'';const freeze=ws['!freeze']?.ySplit?`<sheetViews><sheetView workbookViewId="0"><pane ySplit="${ws['!freeze'].ySplit}" topLeftCell="A${ws['!freeze'].ySplit+1}" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>`:'';const sheetData=rows.map((row,i)=>`<row r="${i+1}">${row.map((value,j)=>{if(value===null||value===undefined)return '';const ref=`${letters(j)}${i+1}`;return typeof value==='number'?`<c r="${ref}"><v>${value}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t>${esc(value)}</t></is></c>`}).join('')}</row>`).join('');const autoFilter=ws['!autofilter']?.ref?`<autoFilter ref="${esc(ws['!autofilter'].ref)}"/>`:'';return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">${dimension}${freeze}${cols}<sheetData>${sheetData}</sheetData>${autoFilter}</worksheet>`}
export const utils:{aoa_to_sheet(data:CellValue[][]):Worksheet;book_new():Workbook;book_append_sheet(wb:Workbook,ws:Worksheet,name:string):void;sheet_to_json<T extends CellValue[]>(ws:Worksheet,options?:{header?:1;defval?:CellValue;raw?:boolean}):T[]}={aoa_to_sheet(data:CellValue[][]):Worksheet{return {'!data':data}},book_new():Workbook{return {SheetNames:[],Sheets:{}}},book_append_sheet(wb:Workbook,ws:Worksheet,name:string){wb.SheetNames.push(name);wb.Sheets[name]=ws},sheet_to_json<T extends CellValue[]>(ws:Worksheet,options?:{header?:1;defval?:CellValue;raw?:boolean}):T[]{void options;return (ws['!data']??[]) as T[]}}
export function writeFile(workbook:Workbook,filename:string,options?:{bookType?:'xlsx',compression?:boolean}){void options;const sheetNames=workbook.SheetNames;const contentTypes=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${sheetNames.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`;const workbookXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheetNames.map((name,i)=>`<sheet name="${esc(name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`;const rels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheetNames.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}</Relationships>`;const files=[{name:'[Content_Types].xml',content:contentTypes},{name:'_rels/.rels',content:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'},{name:'xl/workbook.xml',content:workbookXml},{name:'xl/_rels/workbook.xml.rels',content:rels},...sheetNames.map((name,i)=>({name:`xl/worksheets/sheet${i+1}.xml`,content:sheetXml(workbook.Sheets[name])}))];const blob=zip(files);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

function textFromBytes(bytes:Uint8Array){return new TextDecoder().decode(bytes)}
function unzipStored(buffer:ArrayBuffer){const bytes=new Uint8Array(buffer);const files:Record<string,string>={};let offset=0;while(offset<bytes.length-30){const sig=bytes[offset]|(bytes[offset+1]<<8)|(bytes[offset+2]<<16)|(bytes[offset+3]<<24);if(sig!==0x04034b50){offset++;continue}const method=bytes[offset+8]|(bytes[offset+9]<<8);const compressed=bytes[offset+18]|(bytes[offset+19]<<8)|(bytes[offset+20]<<16)|(bytes[offset+21]<<24);const nameLen=bytes[offset+26]|(bytes[offset+27]<<8);const extraLen=bytes[offset+28]|(bytes[offset+29]<<8);const name=textFromBytes(bytes.slice(offset+30,offset+30+nameLen));const dataStart=offset+30+nameLen+extraLen;const data=bytes.slice(dataStart,dataStart+compressed);if(method===0)files[name]=textFromBytes(data);offset=dataStart+compressed}return files}
function xmlText(value:string){return value.replace(/<[^>]+>/g,'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&apos;/g,"'")}
function parseSheet(xml:string):CellValue[][]{const rows:CellValue[][]=[];for(const row of xml.matchAll(/<row[^>]*>([\s\S]*?)<\/row>/g)){const values:CellValue[]=[];for(const cell of row[1].matchAll(/<c[^>]*?(?:r="([A-Z]+)\d+")?[^>]*>([\s\S]*?)<\/c>/g)){const col=cell[1]?cell[1].split('').reduce((a,c)=>a*26+c.charCodeAt(0)-64,0)-1:values.length;const body=cell[2];const text=body.includes('<v>')?xmlText(body.match(/<v>([\s\S]*?)<\/v>/)?.[1]??''):xmlText(body.match(/<t[^>]*>([\s\S]*?)<\/t>/)?.[1]??'');const num=Number(text);values[col]=text!==''&&Number.isFinite(num)&&!/^0\d+/.test(text)?num:text}rows.push(values)}return rows}
export function read(buffer:ArrayBuffer,options?:{type?:'array';cellDates?:boolean}){void options;const files=unzipStored(buffer);const workbookXml=files['xl/workbook.xml']??'';const rels=files['xl/_rels/workbook.xml.rels']??'';const relMap:Record<string,string>={};for(const rel of rels.matchAll(/<Relationship[^>]*Id="([^"]+)"[^>]*Target="([^"]+)"/g))relMap[rel[1]]=rel[2];const wb:Workbook={SheetNames:[],Sheets:{}};for(const sheet of workbookXml.matchAll(/<sheet[^>]*name="([^"]+)"[^>]*r:id="([^"]+)"/g)){const name=sheet[1];const target=relMap[sheet[2]]??`worksheets/sheet${wb.SheetNames.length+1}.xml`;const path=`xl/${target.replace(/^\/?/,'')}`;wb.SheetNames.push(name);wb.Sheets[name]={'!data':parseSheet(files[path]??'')}}return wb}
