import crypto from 'node:crypto'
import {getAccurateConfig,validateAccurateHost} from './config.js'
import type {AccurateCompany} from './types.js'
const hostCache=new Map<AccurateCompany,string>()
let active=0;const queue:(()=>void)[]=[]
async function limited<T>(fn:()=>Promise<T>){if(active>=4)await new Promise<void>(r=>queue.push(r));active++;try{return await fn()}finally{active--;queue.shift()?.()}}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms))
function headers(secret:string,token:string){const timestamp=Math.floor(Date.now()/1000).toString();const signature=crypto.createHmac('sha256',secret).update(timestamp).digest('hex');return {Authorization:`Bearer ${token}`,'X-Api-Timestamp':timestamp,'X-Api-Signature':signature,'X-Language-Profile':'ID',Accept:'application/json'}}
export class AccurateApiError extends Error{constructor(message:string,public status=500){super(message)}}
function sanitize(status:number){if(status===401)return 'Token tidak valid';if(status===403)return 'Signature tidak valid';if(status===408)return 'Request timeout';if(status===429)return 'Rate limit Accurate tercapai';if(status>=500)return 'Accurate tidak dapat diakses';return 'Koneksi Accurate gagal. Periksa token, signature, dan host.'}
export async function accurateRequest<T>(company:AccurateCompany,path:string,params:Record<string,string|number>={}){return limited(async()=>{const cfg=getAccurateConfig(company);if(!cfg.ok)throw new AccurateApiError(cfg.message,400);let host=hostCache.get(company)??cfg.host;let redirected=false;for(let retry=0;retry<=2;retry++){const url=new URL(path,host);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,String(v)));const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{method:'GET',headers:headers(cfg.signatureSecret,cfg.apiToken),redirect:'manual',signal:controller.signal});if(response.status===308&&!redirected){const location=response.headers.get('location');if(!location)throw new AccurateApiError('Host redirect Accurate tidak valid',308);const next=validateAccurateHost(new URL(location,url).origin);hostCache.set(company,next);host=next;redirected=true;continue}if(response.status===429&&retry<2){await sleep(500*2**retry);continue}if(!response.ok)throw new AccurateApiError(sanitize(response.status),response.status);return await response.json() as T}catch(error){if(error instanceof AccurateApiError)throw error;if((error as Error).name==='AbortError')throw new AccurateApiError('Request timeout',408);throw new AccurateApiError('Accurate tidak dapat diakses',503)}finally{clearTimeout(timeout)}}throw new AccurateApiError('Rate limit Accurate tercapai',429)})}
