/* eslint-disable @typescript-eslint/no-explicit-any */
import bcrypt from 'bcryptjs'
import crypto from 'node:crypto'
import {loadUsers,normalizeEmail,saveUsers,validEmail,type AccessRole} from './_lib/access.js'
import {failure,json,method,requireAdmin,send} from './_lib/http.js'
const roles=['SUPER_ADMIN','ACCOUNTING','MANAGEMENT']
const safe=(user:any)=>{const {passwordHash,...result}=user;void passwordHash;return result}
const validate=(body:any,passwordRequired:boolean)=>{const email=normalizeEmail(body.email);if(!String(body.name??'').trim())return 'Nama wajib diisi.';if(!validEmail(email))return 'Format email tidak valid.';if(!roles.includes(body.role))return 'Role tidak valid.';if((passwordRequired||body.password)&&String(body.password??'').length<8)return 'Password minimal 8 karakter.';return null}
export default async function handler(req:any,res:any){if(!method(req,res,['GET','POST','PATCH','DELETE']))return;try{const admin=await requireAdmin(req,res);if(!admin)return;let users=await loadUsers();if(req.method==='GET'){send(res,200,{users:users.map(safe)});return}const body=await json(req);if(req.method==='POST'){const error=validate(body,true),email=normalizeEmail(body.email);if(error){send(res,400,{message:error});return}if(users.some(user=>user.email===email)){send(res,409,{message:'Email sudah terdaftar.'});return}const now=new Date().toISOString();const user={id:crypto.randomUUID(),name:String(body.name).trim(),email,passwordHash:await bcrypt.hash(String(body.password),12),role:body.role as AccessRole,active:true,createdAt:now,updatedAt:now};await saveUsers([...users,user]);send(res,201,{user:safe(user)});return}const user=users.find(item=>item.id===String(body.id??req.query?.id??''));if(!user){send(res,404,{message:'Pengguna tidak ditemukan.'});return}if(req.method==='DELETE'){if(user.id===admin.id&&user.role==='SUPER_ADMIN'){send(res,400,{message:'ADMIN tidak dapat menghapus akun yang sedang digunakan.'});return}await saveUsers(users.filter(item=>item.id!==user.id));send(res,200,{success:true});return}if(user.id===admin.id&&(body.active===false||body.role&&body.role!=='SUPER_ADMIN')){send(res,400,{message:'ADMIN tidak dapat menonaktifkan atau menurunkan role akun yang sedang digunakan.'});return}const next={...user,...(body.name!==undefined?{name:String(body.name).trim()}:{}),...(body.email!==undefined?{email:normalizeEmail(body.email)}:{}),...(body.role!==undefined?{role:body.role}:{}),...(body.active!==undefined?{active:Boolean(body.active)}:{}),updatedAt:new Date().toISOString()};const error=validate(next,false);if(error){send(res,400,{message:error});return}if(users.some(item=>item.id!==user.id&&item.email===next.email)){send(res,409,{message:'Email sudah terdaftar.'});return}if(body.password)next.passwordHash=await bcrypt.hash(String(body.password),12);users=users.map(item=>item.id===user.id?next:item);await saveUsers(users);send(res,200,{user:safe(next)})}catch(error){failure(res,error)}}
